### Numpy Array

In [3]:
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [1]:
lst = [1,2,3,4,5,6]
type(lst)

list

In [6]:
 na = np.array(lst)
na

array([1, 2, 3, 4, 5, 6])

In [7]:
type(na)

numpy.ndarray

In [8]:
# Single Dimension , 1d Array
na.shape

(6,)

In [12]:
# Two dimensional Array

nested_list = [[1,2,3,4],[5,6,7,8],[9,2,5,7]]
na1 = np.array(nested_list)
na1


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 5, 7]])

In [10]:
na1.shape

(3, 4)

In [13]:
na1.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 5, 7]])

In [15]:
### Three Dimensional
na1.reshape(2,3,2) # (item,Row,Column)

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 2],
        [5, 7]]])

In [16]:
na1.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [5, 7]]])

In [21]:
np.array(['Bharat',4,7,8])

array(['Bharat', '4', '7', '8'], dtype='<U11')

In [24]:
np.array(["a",4,7])

array(['a', '4', '7'], dtype='<U11')

In [28]:
np.array([4,5,6]).dtype

dtype('int32')

In [31]:
### Minimum Dimensions =2 

np.array([1,2,3,4,5,6,7], ndmin =4) #ndmin --> Number of Dimensions

array([[[[1, 2, 3, 4, 5, 6, 7]]]])

In [32]:
# Data Type parameters

np.array([1,2,3,4,5,6,7], dtype=float)

array([1., 2., 3., 4., 5., 6., 7.])

In [33]:
np.array([1,2,3,4,5,6,7], dtype=object)

array([1, 2, 3, 4, 5, 6, 7], dtype=object)

In [34]:
np.array([1,2,3,4,5,6,7], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [36]:
np.array([1,2,3,4,5,6,7], dtype=int).dtype

dtype('int32')

In [37]:
np.array([1,2,3,4,5,6,7], dtype='int64')

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [40]:
np.array([1,2,3,4,5,6,7], dtype=np.float64)

array([1., 2., 3., 4., 5., 6., 7.])

In [39]:
np.array([1,2,3,4,5,6,7], dtype=np.float64).dtype

dtype('float64')

#### Data Type Consist of more than one elements

In [41]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [42]:
type(x[1][0])

numpy.int16

In [43]:
na1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 5, 7]])

In [44]:
na1[1:3]

array([[5, 6, 7, 8],
       [9, 2, 5, 7]])

In [49]:
na1[1:3,0:2]

array([[5, 6],
       [9, 2]])

In [54]:
na5 = na1.reshape(4,3)

In [55]:
na5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 5, 7]])

In [56]:
na5[1:3,0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
na5[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [58]:
na5[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [60]:
na5[1:3,1:]

array([[5, 6],
       [8, 9]])

In [67]:
na5[1:3,0::2]

array([[4, 6],
       [7, 9]])

In [68]:
na5[1:3,[0,2]]

array([[4, 6],
       [7, 9]])

In [69]:
na5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 5, 7]])

In [74]:
na5[0::3,[0,2]]

array([[1, 3],
       [2, 7]])

### Creating an array from the subclasses:

In [75]:
issubclass(np.matrix,np.ndarray) # TO check if conversion is possible or not.

True

In [78]:
np.mat(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [81]:
np.mat('1 2 ; 3 4')

matrix([[1, 2],
        [3, 4]])

## numpy.asarray

The difference between the "array" and "asarray"

In [82]:
arr1 = np.array([1,2,3])

In [83]:
arr2 = np.asarray([1,2,3])

In [84]:
arr1 == arr2

array([ True,  True,  True])

In [86]:
arr1 is arr2 # "is "This is the keyword used to test if two variables refer to the same object.

False

In [110]:
dt = [1,2,3,4,5,6,7]
original_arry = np.asarray(dt)

print('Origional Array Data is:',original_arry)

narry = np.array(original_arry)
narry[1]=10
print('Normal Array is:')
print('Origional Array Data is:',original_arry)

asarry = np.asarray(original_arry)
asarry[2]=20

print('AsArray is:')
print('Origional Array Data is:',original_arry)

Origional Array Data is: [1 2 3 4 5 6 7]
Normal Array is:
Origional Array Data is: [1 2 3 4 5 6 7]
AsArray is:
Origional Array Data is: [ 1  2 20  4  5  6  7]


In [105]:
import numpy as np

dt = [ 2, 3, 4, 5, 6]
# creating array
a = np.array(dt)
print("Original array : ",a)

# assigning value to np.array
np_array = np.array(a)
a[3] = 0
print("np.array Array : ",np_array)

# assigning value to np.asarray
np_asrray = np.asarray(a)
a[3] = 0
print("np.asarray Array : ",np_asrray)

Original array :  [2 3 4 5 6]
np.array Array :  [2 3 4 5 6]
np.asarray Array :  [2 3 4 0 6]


array([5, 6, 9])

### numpy.fromfunction

Construct an array by executing a function over each coordinate.

In [113]:
a = lambda i,j : i==j
a

<function __main__.<lambda>(i, j)>

In [114]:
a(3,3)

True

In [115]:
np.fromfunction(lambda i,j : i==j, (3,3),dtype=int)

#shape(3,3) will provide the below data
# 00 01 02
# 10 11 12
# 20 21 22

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [119]:
np.fromfunction(lambda i,j : i*j, (3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])