In [1]:
# is vs == Difference
lst = ['Bharat','Bharat1','Bharat2']
lst1= ['Bharat','Bharat1','Bharat2']

lst == lst1


True

In [2]:
# is vs == Difference
lst2 = ['Bharat','Bharat1','Bharat2']
lst3= ['Bharat','Bharat1','Bharat2']

lst2 is lst3

False

In [8]:
## "Is" keyword is going to check if we are referencing to the same object or not.

# is vs == Difference
lst2 = ['Bharat','Bharat1','Bharat2']
lst3= lst2

lst2 is lst3

True

In [9]:
print('lst2:',lst2)
print('lst3:',lst3)
lst3[0]='Sunil'
print('After the-- lst3[0]="Sunil" --Operation')
print('lst3:',lst3)
print('lst2:',lst2)

#Both the variables value got chenged because both the variables are referenceing to the same variable.

lst2: ['Bharat', 'Bharat1', 'Bharat2']
lst3: ['Bharat', 'Bharat1', 'Bharat2']
After the-- lst3[0]="Sunil" --Operation
lst3: ['Sunil', 'Bharat1', 'Bharat2']
lst2: ['Sunil', 'Bharat1', 'Bharat2']


In [24]:
a = 10
b = a
a is b

True

In [39]:
import numpy as np
#### Shallow Copy  vs Deep Copy
## Shallow copy

a = np.array([1,2,3,4])
b = a
print('a:',a)
print('b:',b)
print('b[0]:',b[0])
b[0] = 9
print('b:',b)
print('a:',a) # THe value of the "a" is also got changed because both of the variables are pointing to the same memory location.

a: [1 2 3 4]
b: [1 2 3 4]
b[0]: 1
b: [9 2 3 4]
a: [9 2 3 4]


In [40]:
### Deep copy

c = np.array([1,2,3,4])
d = c.copy() # We are creating the value in different memory location.
print('c:',c)
print('d:',d)
print('d[0]:',d[0])
d[0] = 8
print('c:',c)
print('d:',d) # The value of the "c" did not got changed because both the variables are not pointing to the same memory location.

c: [1 2 3 4]
d: [1 2 3 4]
d[0]: 1
c: [1 2 3 4]
d: [8 2 3 4]


In [43]:
## np.array vs np.asarray

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [45]:
np.asarray(a) is a # Because it referencing to the same memory location.

True

In [48]:
np.array(a) is a # Because it is copying the value and create in the values in the different memory location.

False

In [50]:
# np.asanyarray

np.asanyarray([1,2])



array([1, 2])

## Data Types

In [51]:
import numpy as np
my_list = [1,2,3,4,5,6,7]
arr = np.array(my_list)
print("Type/Class of the object:",type(arr)) # type() provides the class of the object
print("Here is the victor\n--------------------------\n",arr)

Type/Class of the object: <class 'numpy.ndarray'>
Here is the victor
--------------------------
 [1 2 3 4 5 6 7]


In [55]:
my_mat = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
mat = np.array(my_mat)
print("Type/Class of the object:",type(mat)) # type() provides the class of the object
print("Here is the victor\n--------------------------\n",mat)
print("Dimension of the matrix:",mat.ndim,sep ='') # It provides the dimension of the array
print("Size of the matrix:",mat.size,sep ='') # It provides the number of elements in the matrix
print("Shape of the matrix:",mat.shape,sep ='') # It provides the shape of the matrix
print("Data type of the matrix:",mat.dtype,sep ='') # It provides the data type of the matrix

Type/Class of the object: <class 'numpy.ndarray'>
Here is the victor
--------------------------
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of the matrix:2
Size of the matrix:12
Shape of the matrix:(3, 4)
Data type of the matrix:int32


## arange and linspace

In [58]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [62]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
np.arange(20,5,-2)

array([20, 18, 16, 14, 12, 10,  8,  6])

In [59]:
print("A series of number:",type(np.arange(0,10,2)))
np.arange(5,16,2.3)

A series of number: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [64]:
# np.linspace()

np.linspace(0,10,5) # It is going to provide the equal numbers based on the parameters("5") between the "start"(0) and "end"(10) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [73]:
np.linspace(1,15,num=10,endpoint=False,retstep=True)

(array([ 1. ,  2.4,  3.8,  5.2,  6.6,  8. ,  9.4, 10.8, 12.2, 13.6]), 1.4)

In [74]:
np.linspace(1,15,num=10,endpoint=True,retstep=True)

(array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
         8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ]),
 1.5555555555555556)

In [75]:
np.linspace(1,15,num=10,endpoint=True,retstep=False)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [77]:
np.logspace(2,3,num=10)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [81]:
np.logspace(2,3,num=10,base=2)

array([4.        , 4.32023896, 4.66611616, 5.0396842 , 5.44316   ,
       5.87893797, 6.34960421, 6.85795186, 7.4069977 , 8.        ])

# Matrix Creation

In [65]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.ones((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [70]:
np.eye(5)# It provides the identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
print("Vector of zeroes\n------------------")
print(np.zeros(5))

In [83]:
## Extract a digonal or construct a digonal array
x = np.arange(16).reshape((4,4))

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
x.diagonal()

array([ 0,  5, 10, 15])

In [86]:
np.diag(x)

array([ 0,  5, 10, 15])

In [97]:
x.diagonal(offset=0,axis1=0,axis2=1)

array([ 4,  9, 14])

In [98]:
np.fliplr(x).diagonal() # Horizontal flip

array([ 3,  6,  9, 12])

In [99]:
np.flipud(x).diagonal() # Vertical flip

array([12,  9,  6,  3])

In [102]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
np.diag(x,k=1)

array([ 1,  6, 11])

In [101]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [103]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [104]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [105]:
np.diagflat([1,2],k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [107]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [112]:
np.tri(3,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [114]:
np.tri(3,5,1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]])

In [115]:
np.tri(3,5,2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

## Random Number Generation

In [119]:
# Range 0 to 1
np.random.rand(2,3)

array([[0.12184055, 0.33665664, 0.31099182],
       [0.3460382 , 0.23106779, 0.39863743]])

In [121]:
# Standard normal distribution
# Range from 3 to -3
np.random.randn(2,3)

array([[-0.70372445,  1.60332857, -0.45628843],
       [-0.91504183,  1.31938222, -0.0211366 ]])

In [123]:
np.random.randint(1,10)

6

In [124]:
np.random.randint(1,100,5)

array([35, 22, 22, 64, 38])

In [118]:

print("Random Number Generation (from uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random number  


Random Number Generation (from uniform distribution)
[[0.49450689 0.60077086 0.67087138]
 [0.11063696 0.13470383 0.38063223]]


## Reshaping

In [125]:
from numpy.random import randint as ri

a = ri(1,1000,30)
b = a.reshape(2,3,5)
b

array([[[ 63, 133, 965, 420,  29],
        [973, 828, 899, 421, 887],
        [492,  96, 738, 393, 481]],

       [[180, 902,  43, 658, 677],
        [421, 334, 576, 750, 350],
        [400, 734, 470, 600,  67]]])

In [135]:
c = a.reshape(6,5) #-19878
c

array([[ 63, 133, 965, 420,  29],
       [973, 828, 899, 421, 887],
       [492,  96, 738, 393, 481],
       [180, 902,  43, 658, 677],
       [421, 334, 576, 750, 350],
       [400, 734, 470, 600,  67]])

In [139]:
c = a.reshape(6,-19878) #If we provide the - number, then it will by default it will take the correct number for row and column
print(c.shape)
c

(6, 5)


array([[ 63, 133, 965, 420,  29],
       [973, 828, 899, 421, 887],
       [492,  96, 738, 393, 481],
       [180, 902,  43, 658, 677],
       [421, 334, 576, 750, 350],
       [400, 734, 470, 600,  67]])

In [145]:
# sorting

a = np.random.randint(1,100,6)

print(a)
print(np.sort(a))

[20 76 24 15 94 84]
[15 20 24 76 84 94]


In [146]:
a.max()

94

In [147]:
a.min()

15

In [148]:
a.argmax() # prints the maximum number index

4

In [150]:
d = a.reshape(2,3)
d

array([[20, 76, 24],
       [15, 94, 84]])

In [152]:
d.max(axis=1)

array([76, 94])

In [155]:
b = np.random.randint(1,100,30).reshape(5,6)
b

array([[84, 73, 30, 17,  2, 72],
       [ 9, 85, 97, 73, 88, 59],
       [ 3, 58, 41, 52, 25, 97],
       [76, 32,  6, 24, 41, 32],
       [46, 21, 69, 29, 99, 59]])

In [161]:
b[2:4,2:4]

array([[41, 52],
       [ 6, 24]])

## Universal Functions

In [163]:
b

array([[84, 73, 30, 17,  2, 72],
       [ 9, 85, 97, 73, 88, 59],
       [ 3, 58, 41, 52, 25, 97],
       [76, 32,  6, 24, 41, 32],
       [46, 21, 69, 29, 99, 59]])

In [164]:
b*2 # Each elements in the matrix are getting multiplied by 2

array([[168, 146,  60,  34,   4, 144],
       [ 18, 170, 194, 146, 176, 118],
       [  6, 116,  82, 104,  50, 194],
       [152,  64,  12,  48,  82,  64],
       [ 92,  42, 138,  58, 198, 118]])

In [165]:
c = np.random.randint(1,100,30).reshape(5,6)
c

array([[29, 57, 66, 75, 91, 30],
       [14, 32, 12, 98, 44, 96],
       [69, 66,  1, 14, 21, 55],
       [10, 50, 82, 35, 70, 91],
       [61, 39, 41,  6, 11, 21]])

In [166]:
b+c

array([[113, 130,  96,  92,  93, 102],
       [ 23, 117, 109, 171, 132, 155],
       [ 72, 124,  42,  66,  46, 152],
       [ 86,  82,  88,  59, 111, 123],
       [107,  60, 110,  35, 110,  80]])

In [170]:
d = np.random.randint(1,20,9).reshape(3,3)
d

array([[10, 11, 17],
       [10, 15, 11],
       [13,  4,  8]])

In [171]:
e = np.random.randint(1,20,9).reshape(3,3)
e

array([[18, 18, 16],
       [ 9, 11,  2],
       [ 7,  2,  5]])

In [172]:
d@e # Matrix Multiplication

array([[398, 335, 267],
       [392, 367, 245],
       [326, 294, 256]])

In [173]:
d*e

array([[180, 198, 272],
       [ 90, 165,  22],
       [ 91,   8,  40]])

In [178]:
e/0

C:\Users\Bharat-PC\AppData\Local\Temp\ipykernel_10232\1449559184.py:1: RuntimeWarning: divide by zero encountered in true_divide
  e/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

## Broadcasting

In [186]:
f = np.random.randint(0,100,30)
f

array([47, 88, 64, 18,  0,  7, 91, 40, 17, 76, 19, 20, 85, 48, 83, 15, 28,
       24, 80, 75, 49, 79, 32, 38, 96,  6, 75, 82,  9, 24])

In [187]:
f[3]

18

In [188]:
f[3:15]=100 # this is called as broadcasting.
f

array([ 47,  88,  64, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100,  15,  28,  24,  80,  75,  49,  79,  32,  38,  96,   6,
        75,  82,   9,  24])

In [184]:
f

array([  3,  79,  60, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [190]:
d

array([[10, 11, 17],
       [10, 15, 11],
       [13,  4,  8]])

In [191]:
e

array([[18, 18, 16],
       [ 9, 11,  2],
       [ 7,  2,  5]])

In [192]:
np.fmod(d,e) # Reminder of the division

array([[10, 11,  1],
       [ 1,  4,  1],
       [ 6,  0,  3]], dtype=int32)

## Subseting

In [193]:
g = np.random.randint(0,100,30)
g

array([12, 13, 80, 53, 83, 17, 89, 32, 59, 16, 50, 19, 44, 95, 10, 46, 85,
       93, 72, 98,  1, 39, 15, 39, 21, 92, 86, 86, 18,  9])

In [196]:
h=np.sort(g)
h

array([ 1,  9, 10, 12, 13, 15, 16, 17, 18, 19, 21, 32, 39, 39, 44, 46, 50,
       53, 59, 72, 80, 83, 85, 86, 86, 89, 92, 93, 95, 98])

In [198]:
h > 30

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [200]:
h[h>30] # We will only going to get the true values

array([32, 39, 39, 44, 46, 50, 53, 59, 72, 80, 83, 85, 86, 86, 89, 92, 93,
       95, 98])